In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('c:/Users/Admin/Downloads/chatgpt_style_reviews_dataset.xlsx - Sheet1.csv')
df

,date,title,review,rating,username,helpful_votes,review_length,platform,language,location,version,verified_purchase
0,2024-09-06,Claim who accept.,Every quite sense including six lot have never...,4,morrowthomas,30,22,Flipkart,ar,Nepal,3.8.4,No
1,3/7/2025,Growth pretty wish.,Ask develop bag also his worker pass. Expert w...,4,sheakimberly,120,22,Flipkart,ar,Guinea,5.2.6,Yes
2,########,What then spend offer reason whom none.,If customer address region try near risk next ...,5,katherineali,130,21,Flipkart,es,Kuwait,3.6.5,No
3,########,Say dog drug enter director strong student.,To television loss election him small detail r...,1,eric11,72,26,Amazon,pt,Uruguay,5.7.2,No
4,########,Purpose here beyond.,Pass share must amount lot per manage world to...,5,chloe42,123,27,Amazon,zh,Mayotte,5.8.6,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,########,Father who tax.,Government card history suddenly save theory s...,5,amassey,109,22,App Store,en,Micronesia,2.3.4,Yes
246,########,Remain movement bit step direction give reduce.,Court control million hundred offer total hit ...,5,stevenandrews,26,23,Website,fr,Austria,3.5.3,No
247,########,Form now then watch certain.,Just opportunity ask yet against large practic...,1,michelle90,67,24,App Store,ru,Rwanda,3.9.6,No
248,3/7/2024,Recent catch gas benefit great religious.,Onto simple audience as including claim create...,5,victor24,29,19,Amazon,zh,Iran,4.9.2,No


In [3]:
df.shape

(250, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   date               250 non-null    object
 1   title              250 non-null    object
 2   review             250 non-null    object
 3   rating             250 non-null    int64 
 4   username           250 non-null    object
 5   helpful_votes      250 non-null    int64 
 6   review_length      250 non-null    int64 
 7   platform           250 non-null    object
 8   language           250 non-null    object
 9   location           250 non-null    object
 10  version            250 non-null    object
 11  verified_purchase  250 non-null    object
dtypes: int64(3), object(9)
memory usage: 23.6+ KB


In [5]:
df.describe()

,rating,helpful_votes,review_length
count,250.000000,250.000000,250.000000
mean,2.980000,94.416000,20.852000
std,1.465671,57.020842,3.459185
min,1.000000,0.000000,13.000000
25%,2.000000,42.250000,18.000000
50%,3.000000,95.000000,21.000000
75%,4.000000,140.500000,23.000000
max,5.000000,200.000000,29.000000


In [6]:
#convert date column into date and time
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [7]:
df.info()   # Column names, non-null counts, data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   date               2 non-null      datetime64[ns]
 1   title              250 non-null    object        
 2   review             250 non-null    object        
 3   rating             250 non-null    int64         
 4   username           250 non-null    object        
 5   helpful_votes      250 non-null    int64         
 6   review_length      250 non-null    int64         
 7   platform           250 non-null    object        
 8   language           250 non-null    object        
 9   location           250 non-null    object        
 10  version            250 non-null    object        
 11  verified_purchase  250 non-null    object        
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 23.6+ KB


In [8]:
df.describe()  # Summary for numerical columns

,date,rating,helpful_votes,review_length
count,2,250.000000,250.000000,250.000000
mean,2024-08-21 12:00:00,2.980000,94.416000,20.852000
min,2024-08-06 00:00:00,1.000000,0.000000,13.000000
25%,2024-08-13 18:00:00,2.000000,42.250000,18.000000
50%,2024-08-21 12:00:00,3.000000,95.000000,21.000000
75%,2024-08-29 06:00:00,4.000000,140.500000,23.000000
max,2024-09-06 00:00:00,5.000000,200.000000,29.000000
std,NaN,1.465671,57.020842,3.459185


In [9]:
df.isnull().sum()

date                 248
title                  0
review                 0
rating                 0
username               0
helpful_votes          0
review_length          0
platform               0
language               0
location               0
version                0
verified_purchase      0
dtype: int64

In [10]:
df.drop('date', axis=1, inplace=True)

In [11]:
df.head()

,title,review,rating,username,helpful_votes,review_length,platform,language,location,version,verified_purchase
0,Claim who accept.,Every quite sense including six lot have never...,4,morrowthomas,30,22,Flipkart,ar,Nepal,3.8.4,No
1,Growth pretty wish.,Ask develop bag also his worker pass. Expert w...,4,sheakimberly,120,22,Flipkart,ar,Guinea,5.2.6,Yes
2,What then spend offer reason whom none.,If customer address region try near risk next ...,5,katherineali,130,21,Flipkart,es,Kuwait,3.6.5,No
3,Say dog drug enter director strong student.,To television loss election him small detail r...,1,eric11,72,26,Amazon,pt,Uruguay,5.7.2,No
4,Purpose here beyond.,Pass share must amount lot per manage world to...,5,chloe42,123,27,Amazon,zh,Mayotte,5.8.6,No


In [12]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [13]:
import re
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag
from nltk.corpus import wordnet



stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
negators = {"no","nor","not","don't","ain","aren","couldn","didn","doesn","hadn","hasn","haven","isn","mightn","mustn","needn","shan","shouldn","wasn","weren","won","wouldn"}
stop_words = stop_words - negators

def _to_wn(pos):
  return {"J": wordnet.ADJ, "V": wordnet.VERB, "N": wordnet.NOUN, "R": wordnet.ADV}.get(pos[0], wordnet.NOUN)

def preprocess_text(text):

    if pd.isnull(text):
      return ""
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers
    text = re.sub(r"[^a-zA-Z\s ']", " ", text)
    #collapse extra spaces
    text = re.sub(r"\s+", " ", text)
    # Tokenize
    tokens = text.split()
    #remove stopwords but keep negators
    tokens = [token for token in tokens if token not in stop_words or token in negators]
    # Lemmatize
    tagged_tokens = pos_tag(tokens)
    lemmatized_tokens = [lemmatizer.lemmatize(token, _to_wn(pos)) for token, pos in tagged_tokens]
    return " ".join(lemmatized_tokens)

df['cleaned_reviews']= df['review'].apply (preprocess_text)


In [14]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 "couldn't",
 'd',
 'did',
 "didn't",
 'do',
 'does',
 "doesn't",
 'doing',
 'don',
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 "hadn't",
 'has',
 "hasn't",
 'have',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 "mightn't",
 'more',
 'most',
 "mustn't",
 'my',
 'myself',
 "needn't",
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's

In [15]:
#TEXT PREPROCESSING SETUP
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

negators = {"no","nor","not","don't","didn","doesn","isn","wasn","weren"}
stop_words = stop_words - negators

def _to_wn(pos):
    return {
        "J": wordnet.ADJ,
        "V": wordnet.VERB,
        "N": wordnet.NOUN,
        "R": wordnet.ADV
    }.get(pos[0], wordnet.NOUN)

def preprocess_text(text):
    if pd.isnull(text):
        return ""
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    tokens = text.split()
    tokens = [t for t in tokens if t not in stop_words or t in negators]
    tagged = pos_tag(tokens)
    lemmatized = [lemmatizer.lemmatize(w, _to_wn(p)) for w, p in tagged]
    return " ".join(lemmatized)

df["cleaned_reviews"] = df["review"].apply(preprocess_text)


In [16]:
#. HANDLE MISSING VALUES
df.fillna({"title": "No Title", "platform": "Unknown"}, inplace=True)
     

# CREATE SENTIMENT LABEL FROM RATING
def get_sentiment_label(r):
    if r >= 4: return "positive"
    elif r <= 2: return "negative"
    else: return "neutral"

df["sentiment"] = df["rating"].apply(get_sentiment_label)
     

In [17]:
#SAVE CLEANED DATASET
df.to_csv("processed_cleaned_reviews.csv", index=False)
print("✅ Saved processed_cleaned_reviews.csv")

✅ Saved processed_cleaned_reviews.csv


In [18]:
import pandas as pd
import numpy as np
import re
import joblib
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag
from nltk.corpus import wordnet

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import resample
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report, accuracy_score

In [19]:
#LOAD FOR MODEL TRAINING
df = pd.read_csv("processed_cleaned_reviews.csv")


In [20]:
df = df[["cleaned_reviews", "sentiment"]].dropna()

print("\nBefore balancing:\n", df["sentiment"].value_counts())


Before balancing:
 sentiment
negative    97
positive    96
neutral     57
Name: count, dtype: int64


In [21]:
# BALANCE DATA USING UPSAMPLING
max_count = df["sentiment"].value_counts().max()
balanced_parts = []

for label, group in df.groupby("sentiment"):
    if len(group) < max_count:
        up = resample(group, replace=True, n_samples=max_count, random_state=42)
        balanced_parts.append(up)
    else:
        balanced_parts.append(group)

df_balanced = pd.concat(balanced_parts).sample(frac=1, random_state=42).reset_index(drop=True)

print("\nAfter balancing:\n", df_balanced["sentiment"].value_counts())
     


After balancing:
 sentiment
negative    97
positive    97
neutral     97
Name: count, dtype: int64


In [22]:
# HYBRID SENTIMENT FIX (MODEL + RULE BASED)
# SIMPLE SENTIMENT LEXICON
positive_words = {
    "good", "great", "excellent", "awesome", "nice", "amazing",
    "perfect", "love", "super", "best", "fantastic", "wonderful",
    "better", "fast", "smooth", "happy"
}

negative_words = {
    "bad", "worst", "poor", "slow", "terrible", "awful",
    "problem", "issue", "bug", "crash", "fail", "failed",
    "error", "lag", "laggy", "hate"
}

neutral_words = {
    "ok", "okay", "average", "fine", "normal", "decent", "regular"
}

In [23]:
 #TRAIN TEST SPLIT

X = df_balanced["cleaned_reviews"]
y = df_balanced["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
     

In [24]:
#TF-IDF VECTORIZATION
vectorizer = TfidfVectorizer(max_features=20000, ngram_range=(1,2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [25]:
#LOGISTIC REGRESSION MODEL
model = LogisticRegression(max_iter=1000, solver="lbfgs")
model.fit(X_train_vec, y_train)


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [26]:
cv_scores = cross_val_score(model, X_train_vec, y_train, cv=5, scoring="accuracy")
print("\nCV Accuracy:", cv_scores.mean())


CV Accuracy: 0.693709528214616


In [27]:
#EVALUATION
y_pred = model.predict(X_test_vec)

print("\nCLASSIFICATION REPORT:\n", classification_report(y_test, y_pred))
print("CONFUSION MATRIX:\n", confusion_matrix(y_test, y_pred))


CLASSIFICATION REPORT:
               precision    recall  f1-score   support

    negative       0.64      0.74      0.68        19
     neutral       0.94      0.85      0.89        20
    positive       0.74      0.70      0.72        20

    accuracy                           0.76        59
   macro avg       0.77      0.76      0.77        59
weighted avg       0.77      0.76      0.77        59

CONFUSION MATRIX:
 [[14  1  4]
 [ 2 17  1]
 [ 6  0 14]]


In [28]:
#SAVE MODEL & VECTORIZER
joblib.dump(model, "text_classifier_balanced.joblib")
joblib.dump(vectorizer, "vectorizer_balanced.joblib")

print("\n✅ Saved Model & Vectorizer")


✅ Saved Model & Vectorizer


In [29]:
#Hyperparameter tunning

param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],          # Regularization strength
    'penalty': ['l2'],                    # Best for text data
    'solver': ['lbfgs', 'liblinear'],     # Reliable solvers
    'max_iter': [100, 300, 500]
}
grid = GridSearchCV(
    LogisticRegression(),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

grid.fit(X_train_vec, y_train)


best_model = grid.best_estimator_
best_params = grid.best_params_

print("Best Parameters:", best_params)
y_pred = best_model.predict(X_test_vec)

print("✅ Accuracy:", accuracy_score(y_test, y_pred))

print("\n✅ CLASSIFICATION REPORT:\n")
print(classification_report(y_test, y_pred))

print("\n✅ CONFUSION MATRIX:\n")
cm = confusion_matrix(y_test, y_pred)
print(cm)



Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best Parameters: {'C': 0.1, 'max_iter': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
✅ Accuracy: 0.8135593220338984

✅ CLASSIFICATION REPORT:

              precision    recall  f1-score   support

    negative       0.68      0.89      0.77        19
     neutral       1.00      0.85      0.92        20
    positive       0.82      0.70      0.76        20

    accuracy                           0.81        59
   macro avg       0.83      0.81      0.82        59
weighted avg       0.84      0.81      0.82        59


✅ CONFUSION MATRIX:

[[17  0  2]
 [ 2 17  1]
 [ 6  0 14]]


c:\Users\Admin\Desktop\streamlit\Chatgpt_review\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning: 
75 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\streamlit\Chatgpt_review\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\streamlit\Chatgpt_review\.venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Admin\Desktop\

In [30]:
import joblib
joblib.dump(best_model, "tuned_logistic_model.pkl")

['tuned_logistic_model.pkl']

In [31]:
# SMART HYBRID SENTIMENT PREDICTION (FIXED)
positive_words = {
    "good", "great", "excellent", "awesome", "nice", "amazing", "perfect",
    "love", "super", "best", "fantastic", "wonderful", "better", "fast",
    "smooth", "happy"
}

negative_words = {
    "bad", "worst", "poor", "slow", "terrible", "awful",
    "problem", "issue", "bug", "crash", "crashes",
    "fail", "failed", "error", "lag", "laggy", "hate","not good"
}

neutral_words = {
    "ok", "okay", "average", "fine", "normal", "decent", "regular"
}

def smart_predict(text):
    cleaned = preprocess_text(text)
    words = cleaned.split()

    pos_hits = sum(1 for w in words if w in positive_words)
    neg_hits = sum(1 for w in words if w in negative_words)
    neu_hits = sum(1 for w in words if w in neutral_words)

    # ✅ Rule-based first (MOST IMPORTANT FIX)
    if pos_hits > neg_hits:
        return "positive ✅ (rule-based)"
    elif neg_hits > pos_hits:
        return "negative ❌ (rule-based)"
    elif neu_hits > 0:
        return "neutral ⚪ (rule-based)"

    # ✅ Very short text default
    if len(words) <= 2:
        return "neutral ⚪ (short-text default)"

    # ✅ ML Model fallback
    vec = vectorizer.transform([cleaned])
    pred = model.predict(vec)[0]
    return pred + " 🤖 (model)"


In [ ]:
#LIVE SENTENCE TESTING

while True:
    sent = input("\nEnter sentence (or type exit): ")
    if sent.lower().strip() == "exit":
        break
    print("Sentiment =", smart_predict(sent))

Sentiment = neutral ⚪ (short-text default)
